using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Practice.Hangman.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "GuessWords",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Word = table.Column<string>(type: "varchar(100)", nullable: false),
                    WordSize = table.Column<int>(type: "int", nullable: false),
                    Difficulty = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GuessWords", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Players",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Nickname = table.Column<string>(type: "varchar(50)", nullable: false),
                    AvatarUrl = table.Column<string>(type: "varchar(150)", nullable: false),
                    Rank = table.Column<int>(type: "int", nullable: false),
                    RegisteredDate = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Players", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "PlayerGames",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    PlayerId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    GuessWordId = table.Column<int>(type: "int", nullable: false),
                    CurrentScore = table.Column<long>(type: "bigint", nullable: false),
                    TotalAttempts = table.Column<int>(type: "int", nullable: false),
                    AttemptedChars = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SuccessfulAttempts = table.Column<int>(type: "int", nullable: false),
                    GuessedChars = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: false),
                    StartAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    FinishedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PlayerGames", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PlayerGames_GuessWords_GuessWordId",
                        column: x => x.GuessWordId,
                        principalTable: "GuessWords",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PlayerGames_Players_PlayerId",
                        column: x => x.PlayerId,
                        principalTable: "Players",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "PlayerScores",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PlayerId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Rank = table.Column<int>(type: "int", nullable: false),
                    Difficulty = table.Column<int>(type: "int", nullable: false),
                    Score = table.Column<long>(type: "bigint", nullable: false),
                    NumAttempts = table.Column<int>(type: "int", nullable: false),
                    MinTimeWordGuessed = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PlayerScores", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PlayerScores_Players_PlayerId",
                        column: x => x.PlayerId,
                        principalTable: "Players",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "GuessWords",
                columns: new[] { "Id", "Difficulty", "Word", "WordSize" },
                values: new object[,]
                {
                    { 1, 3, "abandonar", 9 },
                    { 2, 1, "abrir", 5 },
                    { 3, 2, "absoluta", 8 },
                    { 4, 2, "absoluto", 8 },
                    { 5, 2, "abuelo", 6 },
                    { 6, 2, "acabar", 6 },
                    { 7, 1, "acaso", 5 },
                    { 8, 2, "acciones", 8 },
                    { 9, 2, "acción", 6 },
                    { 10, 2, "aceptar", 7 },
                    { 11, 2, "acercar", 7 },
                    { 12, 3, "acompañar", 9 },
                    { 13, 2, "acordar", 7 },
                    { 14, 2, "actitud", 7 },
                    { 15, 3, "actividad", 9 },
                    { 16, 1, "acto", 4 },
                    { 17, 2, "actual", 6 },
                    { 18, 2, "actuar", 6 },
                    { 19, 2, "acudir", 6 },
                    { 20, 2, "acuerdo", 7 },
                    { 21, 2, "adelante", 8 },
                    { 22, 2, "además", 6 },
                    { 23, 2, "adquirir", 8 },
                    { 24, 2, "advertir", 8 },
                    { 25, 2, "afectar", 7 },
                    { 26, 2, "afirmar", 7 },
                    { 27, 1, "agua", 4 },
                    { 28, 1, "ahora", 5 },
                    { 29, 1, "aire", 4 },
                    { 30, 2, "alcanzar", 8 },
                    { 31, 2, "alejar", 6 },
                    { 32, 2, "alemana", 7 },
                    { 33, 2, "alemán", 6 },
                    { 34, 1, "algo", 4 },
                    { 35, 2, "alguien", 7 },
                    { 36, 2, "alguna", 6 },
                    { 37, 2, "alguno", 6 },
                    { 38, 1, "algún", 5 },
                    { 39, 1, "alma", 4 },
                    { 40, 1, "alta", 4 },
                    { 41, 1, "alto", 4 },
                    { 42, 2, "altura", 6 },
                    { 43, 1, "amar", 4 },
                    { 44, 1, "ambas", 5 },
                    { 45, 1, "ambos", 5 },
                    { 46, 3, "americana", 9 },
                    { 47, 3, "americano", 9 },
                    { 48, 1, "amiga", 5 },
                    { 49, 1, "amigo", 5 },
                    { 50, 1, "amor", 4 },
                    { 51, 2, "amplia", 6 },
                    { 52, 2, "amplio", 6 },
                    { 53, 1, "andar", 5 },
                    { 54, 2, "animal", 6 },
                    { 55, 1, "ante", 4 },
                    { 56, 2, "anterior", 8 },
                    { 57, 2, "antigua", 7 },
                    { 58, 2, "antiguo", 7 },
                    { 59, 2, "anunciar", 8 },
                    { 60, 2, "análisis", 8 },
                    { 61, 2, "aparecer", 8 },
                    { 62, 2, "apenas", 6 },
                    { 63, 2, "aplicar", 7 },
                    { 64, 2, "apoyar", 6 },
                    { 65, 2, "aprender", 8 },
                    { 66, 3, "aprovechar", 10 },
                    { 67, 1, "aquel", 5 },
                    { 68, 2, "aquella", 7 },
                    { 69, 2, "aquello", 7 },
                    { 70, 1, "aquí", 4 },
                    { 71, 1, "arma", 4 },
                    { 72, 2, "arriba", 6 },
                    { 73, 1, "arte", 4 },
                    { 74, 2, "asegurar", 8 },
                    { 75, 2, "aspecto", 7 },
                    { 76, 2, "asunto", 6 },
                    { 77, 1, "así", 3 },
                    { 78, 3, "atenciones", 10 },
                    { 79, 2, "atención", 8 },
                    { 80, 3, "atreverse", 9 },
                    { 81, 1, "atrás", 5 },
                    { 82, 2, "aumentar", 8 },
                    { 83, 2, "aunque", 6 },
                    { 84, 1, "autor", 5 },
                    { 85, 2, "autora", 6 },
                    { 86, 3, "autoridad", 9 },
                    { 87, 3, "auténtica", 9 },
                    { 88, 3, "auténtico", 9 },
                    { 89, 2, "avanzar", 7 },
                    { 90, 1, "ayer", 4 },
                    { 91, 1, "ayuda", 5 },
                    { 92, 2, "ayudar", 6 },
                    { 93, 1, "azul", 4 },
                    { 94, 2, "añadir", 6 },
                    { 95, 1, "año", 3 },
                    { 96, 1, "aún", 3 },
                    { 97, 1, "baja", 4 },
                    { 98, 1, "bajar", 5 },
                    { 99, 2, "barrio", 6 },
                    { 100, 1, "base", 4 },
                    { 101, 2, "bastante", 8 },
                    { 102, 2, "bastar", 6 },
                    { 103, 1, "beber", 5 },
                    { 104, 1, "bien", 4 },
                    { 105, 2, "blanca", 6 },
                    { 106, 2, "blanco", 6 },
                    { 107, 1, "boca", 4 },
                    { 108, 1, "brazo", 5 },
                    { 109, 1, "buen", 4 },
                    { 110, 2, "buscar", 6 },
                    { 111, 2, "caballo", 7 },
                    { 112, 1, "caber", 5 },
                    { 113, 2, "cabeza", 6 },
                    { 114, 1, "cabo", 4 },
                    { 115, 1, "cada", 4 },
                    { 116, 2, "cadena", 6 },
                    { 117, 1, "caer", 4 },
                    { 118, 1, "calle", 5 },
                    { 119, 1, "cama", 4 },
                    { 120, 2, "cambiar", 7 },
                    { 121, 2, "cambio", 6 },
                    { 122, 2, "caminar", 7 },
                    { 123, 2, "camino", 6 },
                    { 124, 2, "campaña", 7 },
                    { 125, 1, "campo", 5 },
                    { 126, 2, "cantar", 6 },
                    { 127, 2, "cantidad", 8 },
                    { 128, 2, "capaces", 7 },
                    { 129, 3, "capacidad", 9 },
                    { 130, 1, "capaz", 5 },
                    { 131, 2, "capital", 7 },
                    { 132, 1, "cara", 4 },
                    { 133, 3, "caracteres", 10 },
                    { 134, 1, "carne", 5 },
                    { 135, 2, "carrera", 7 },
                    { 136, 1, "carta", 5 },
                    { 137, 2, "carácter", 8 },
                    { 138, 1, "casa", 4 },
                    { 139, 1, "casar", 5 },
                    { 140, 1, "casi", 4 },
                    { 141, 1, "caso", 4 },
                    { 142, 2, "catalán", 7 },
                    { 143, 1, "causa", 5 },
                    { 144, 2, "celebrar", 8 },
                    { 145, 2, "central", 7 },
                    { 146, 2, "centro", 6 },
                    { 147, 2, "cerebro", 7 },
                    { 148, 2, "cerrar", 6 },
                    { 149, 1, "chica", 5 },
                    { 150, 1, "chico", 5 },
                    { 151, 1, "cielo", 5 },
                    { 152, 2, "ciencia", 7 },
                    { 153, 2, "ciento", 6 },
                    { 154, 3, "científica", 10 },
                    { 155, 3, "científico", 10 },
                    { 156, 2, "cierta", 6 },
                    { 157, 2, "cierto", 6 },
                    { 158, 1, "cinco", 5 },
                    { 159, 1, "cine", 4 },
                    { 160, 4, "circunstancia", 13 },
                    { 161, 2, "ciudad", 6 },
                    { 162, 3, "ciudadana", 9 },
                    { 163, 3, "ciudadano", 9 },
                    { 164, 1, "civil", 5 },
                    { 165, 1, "clara", 5 },
                    { 166, 1, "claro", 5 },
                    { 167, 1, "clase", 5 },
                    { 168, 1, "coche", 5 },
                    { 169, 1, "coger", 5 },
                    { 170, 2, "colocar", 7 },
                    { 171, 1, "color", 5 },
                    { 172, 2, "comentar", 8 },
                    { 173, 2, "comenzar", 8 },
                    { 174, 1, "comer", 5 },
                    { 175, 1, "como", 4 },
                    { 176, 3, "compañera", 9 },
                    { 177, 3, "compañero", 9 },
                    { 178, 2, "compañía", 8 },
                    { 179, 2, "completo", 8 },
                    { 180, 2, "comprar", 7 },
                    { 181, 3, "comprender", 10 },
                    { 182, 3, "comprobar", 9 },
                    { 183, 2, "comunes", 7 },
                    { 184, 4, "comunicaciones", 14 },
                    { 185, 4, "comunicación", 12 },
                    { 186, 1, "común", 5 },
                    { 187, 1, "con", 3 },
                    { 188, 2, "concepto", 8 },
                    { 189, 3, "conciencia", 10 },
                    { 190, 2, "concreto", 8 },
                    { 191, 3, "condición", 9 },
                    { 192, 3, "condisiones", 11 },
                    { 193, 2, "conducir", 8 },
                    { 194, 2, "conjunto", 8 },
                    { 195, 2, "conocer", 7 },
                    { 196, 4, "conocimiento", 12 },
                    { 197, 4, "consecuencia", 12 },
                    { 198, 3, "conseguir", 9 },
                    { 199, 3, "conservar", 9 },
                    { 200, 3, "considerar", 10 },
                    { 201, 3, "consistir", 9 },
                    { 202, 3, "constante", 9 },
                    { 203, 3, "constituir", 10 },
                    { 204, 3, "construir", 9 },
                    { 205, 2, "contacto", 8 },
                    { 206, 2, "contar", 6 },
                    { 207, 3, "contemplar", 10 },
                    { 208, 2, "contener", 8 },
                    { 209, 3, "contestar", 9 },
                    { 210, 3, "continuar", 9 },
                    { 211, 2, "contra", 6 },
                    { 212, 3, "contrario", 9 },
                    { 213, 2, "control", 7 },
                    { 214, 3, "controlar", 9 },
                    { 215, 3, "convencer", 9 },
                    { 216, 4, "conversación", 12 },
                    { 217, 3, "convertir", 9 },
                    { 218, 2, "corazón", 7 },
                    { 219, 2, "correr", 6 },
                    { 220, 4, "corresponder", 12 },
                    { 221, 3, "corriente", 9 },
                    { 222, 2, "cortar", 6 },
                    { 223, 1, "cosa", 4 },
                    { 224, 3, "costumbre", 9 },
                    { 225, 1, "crear", 5 },
                    { 226, 2, "crecer", 6 },
                    { 227, 1, "creer", 5 },
                    { 228, 2, "crisis", 6 },
                    { 229, 2, "cruzar", 6 },
                    { 230, 2, "cuadro", 6 },
                    { 231, 1, "cual", 4 },
                    { 232, 3, "cualquier", 9 },
                    { 233, 2, "cuando", 6 },
                    { 234, 2, "cuanto", 6 },
                    { 235, 2, "cuarta", 6 },
                    { 236, 2, "cuarto", 6 },
                    { 237, 2, "cuatro", 6 },
                    { 238, 2, "cubrir", 6 },
                    { 239, 2, "cuenta", 6 },
                    { 240, 2, "cuerpo", 6 },
                    { 241, 3, "cuestiones", 10 },
                    { 242, 2, "cuestión", 8 },
                    { 243, 2, "cultura", 7 },
                    { 244, 2, "cultural", 8 },
                    { 245, 2, "cumplir", 7 },
                    { 246, 1, "cuya", 4 },
                    { 247, 1, "cuyo", 4 },
                    { 248, 1, "cuál", 4 },
                    { 249, 2, "cuánto", 6 },
                    { 250, 2, "célula", 6 },
                    { 251, 1, "cómo", 4 },
                    { 252, 1, "dar", 3 },
                    { 253, 1, "dato", 4 },
                    { 254, 1, "deber", 5 },
                    { 255, 2, "decidir", 7 },
                    { 256, 1, "decir", 5 },
                    { 257, 2, "decisión", 8 },
                    { 258, 2, "declarar", 8 },
                    { 259, 2, "dedicar", 7 },
                    { 260, 1, "dedo", 4 },
                    { 261, 2, "defender", 8 },
                    { 262, 2, "defensa", 7 },
                    { 263, 2, "definir", 7 },
                    { 264, 3, "definitivo", 10 },
                    { 265, 1, "dejar", 5 },
                    { 266, 3, "demasiado", 9 },
                    { 267, 3, "democracia", 10 },
                    { 268, 3, "demostrar", 9 },
                    { 269, 1, "demás", 5 },
                    { 270, 2, "depender", 8 },
                    { 271, 2, "derecha", 7 },
                    { 272, 2, "derecho", 7 },
                    { 273, 3, "desaparecer", 11 },
                    { 274, 3, "desarrollar", 11 },
                    { 275, 3, "desarrollo", 10 },
                    { 276, 3, "desconocer", 10 },
                    { 277, 3, "descubrir", 9 },
                    { 278, 1, "desde", 5 },
                    { 279, 2, "desear", 6 },
                    { 280, 1, "deseo", 5 },
                    { 281, 3, "despertar", 9 },
                    { 282, 2, "después", 7 },
                    { 283, 2, "destino", 7 },
                    { 284, 2, "detener", 7 },
                    { 285, 3, "determinar", 10 },
                    { 286, 2, "diaria", 6 },
                    { 287, 2, "diario", 6 },
                    { 288, 1, "diez", 4 },
                    { 289, 3, "diferencia", 10 },
                    { 290, 3, "diferente", 9 },
                    { 291, 3, "dificultad", 10 },
                    { 292, 2, "difícil", 7 },
                    { 293, 2, "dinero", 6 },
                    { 294, 1, "dios", 4 },
                    { 295, 1, "diosa", 5 },
                    { 296, 3, "dirección", 9 },
                    { 297, 2, "directo", 7 },
                    { 298, 2, "director", 8 },
                    { 299, 3, "directora", 9 },
                    { 300, 2, "dirigir", 7 },
                    { 301, 2, "disponer", 8 },
                    { 302, 3, "distancia", 9 },
                    { 303, 2, "distinto", 8 },
                    { 304, 2, "diverso", 7 },
                    { 305, 1, "doble", 5 },
                    { 306, 2, "doctor", 6 },
                    { 307, 2, "doctora", 7 },
                    { 308, 1, "dolor", 5 },
                    { 309, 1, "don", 3 },
                    { 310, 1, "donde", 5 },
                    { 311, 2, "dormir", 6 },
                    { 312, 1, "dos", 3 },
                    { 313, 1, "duda", 4 },
                    { 314, 2, "durante", 7 },
                    { 315, 1, "duro", 4 },
                    { 316, 1, "día", 3 },
                    { 317, 1, "dónde", 5 },
                    { 318, 1, "echar", 5 },
                    { 319, 3, "económico", 9 },
                    { 320, 1, "edad", 4 },
                    { 321, 2, "efecto", 6 },
                    { 322, 2, "ejemplo", 7 },
                    { 323, 2, "ejército", 8 },
                    { 324, 2, "elección", 8 },
                    { 325, 2, "elegir", 6 },
                    { 326, 2, "elemento", 8 },
                    { 327, 2, "elevar", 6 },
                    { 328, 2, "empezar", 7 },
                    { 329, 2, "empresa", 7 },
                    { 330, 2, "encender", 8 },
                    { 331, 2, "encima", 6 },
                    { 332, 3, "encontrar", 9 },
                    { 333, 3, "encuentro", 9 },
                    { 334, 2, "energía", 7 },
                    { 335, 3, "enfermedad", 10 },
                    { 336, 2, "enfermo", 7 },
                    { 337, 2, "enorme", 6 },
                    { 338, 2, "enseñar", 7 },
                    { 339, 2, "entender", 8 },
                    { 340, 2, "enterar", 7 },
                    { 341, 2, "entonces", 8 },
                    { 342, 2, "entrada", 7 },
                    { 343, 2, "entrar", 6 },
                    { 344, 1, "entre", 5 },
                    { 345, 2, "entregar", 8 },
                    { 346, 2, "enviar", 6 },
                    { 347, 2, "equipo", 6 },
                    { 348, 1, "error", 5 },
                    { 349, 2, "escapar", 7 },
                    { 350, 2, "escribir", 8 },
                    { 351, 2, "escritor", 8 },
                    { 352, 3, "escritora", 9 },
                    { 353, 2, "escuchar", 8 },
                    { 354, 2, "esfuerzo", 8 },
                    { 355, 2, "espacio", 7 },
                    { 356, 2, "espalda", 7 },
                    { 357, 2, "españa", 6 },
                    { 358, 2, "español", 7 },
                    { 359, 2, "española", 8 },
                    { 360, 2, "especial", 8 },
                    { 361, 2, "especie", 7 },
                    { 362, 3, "esperanza", 9 },
                    { 363, 2, "esperar", 7 },
                    { 364, 2, "espíritu", 8 },
                    { 365, 1, "esta", 4 },
                    { 366, 3, "establecer", 10 },
                    { 367, 2, "estado", 6 },
                    { 368, 1, "estar", 5 },
                    { 369, 1, "este", 4 },
                    { 370, 1, "esto", 4 },
                    { 371, 2, "estrella", 8 },
                    { 372, 3, "estructura", 10 },
                    { 373, 2, "estudiar", 8 },
                    { 374, 2, "estudio", 7 },
                    { 375, 1, "etapa", 5 },
                    { 376, 2, "europa", 6 },
                    { 377, 2, "europea", 7 },
                    { 378, 2, "europeo", 7 },
                    { 379, 2, "evidente", 8 },
                    { 380, 2, "evitar", 6 },
                    { 381, 2, "exacta", 6 },
                    { 382, 2, "exacto", 6 },
                    { 383, 2, "exigir", 6 },
                    { 384, 3, "existencia", 10 },
                    { 385, 2, "existir", 7 },
                    { 386, 3, "experiencia", 11 },
                    { 387, 2, "explicar", 8 },
                    { 388, 3, "expresión", 9 },
                    { 389, 2, "extender", 8 },
                    { 390, 2, "exterior", 8 },
                    { 391, 3, "extranjera", 10 },
                    { 392, 3, "extranjero", 10 },
                    { 393, 2, "extraño", 7 },
                    { 394, 2, "extremo", 7 },
                    { 395, 1, "falta", 5 },
                    { 396, 2, "faltar", 6 },
                    { 397, 2, "familia", 7 },
                    { 398, 2, "familiar", 8 },
                    { 399, 2, "famoso", 6 },
                    { 400, 2, "fenómeno", 8 },
                    { 401, 2, "fiesta", 6 },
                    { 402, 2, "figura", 6 },
                    { 403, 1, "fijar", 5 },
                    { 404, 1, "fin", 3 },
                    { 405, 1, "final", 5 },
                    { 406, 1, "flor", 4 },
                    { 407, 1, "fondo", 5 },
                    { 408, 1, "forma", 5 },
                    { 409, 2, "formar", 6 },
                    { 410, 2, "francesa", 8 },
                    { 411, 2, "francia", 7 },
                    { 412, 2, "francés", 7 },
                    { 413, 1, "frase", 5 },
                    { 414, 3, "frecuencia", 10 },
                    { 415, 2, "frente", 6 },
                    { 416, 1, "fría", 4 },
                    { 417, 1, "frío", 4 },
                    { 418, 1, "fuego", 5 },
                    { 419, 2, "fuente", 6 },
                    { 420, 2, "fuerte", 6 },
                    { 421, 2, "fuerza", 6 },
                    { 422, 3, "funcionar", 9 },
                    { 423, 2, "función", 7 },
                    { 424, 3, "fundamental", 11 },
                    { 425, 2, "futuro", 6 },
                    { 426, 1, "fácil", 5 },
                    { 427, 2, "físico", 6 },
                    { 428, 2, "fútbol", 6 },
                    { 429, 1, "ganar", 5 },
                    { 430, 2, "general", 7 },
                    { 431, 1, "gente", 5 },
                    { 432, 1, "gesto", 5 },
                    { 433, 2, "gobierno", 8 },
                    { 434, 1, "golpe", 5 },
                    { 435, 2, "gracia", 6 },
                    { 436, 1, "gran", 4 },
                    { 437, 2, "grande", 6 },
                    { 438, 1, "grave", 5 },
                    { 439, 2, "gritar", 6 },
                    { 440, 1, "grupo", 5 },
                    { 441, 2, "guardar", 7 },
                    { 442, 2, "guerra", 6 },
                    { 443, 2, "gustar", 6 },
                    { 444, 1, "gusto", 5 },
                    { 445, 1, "haber", 5 },
                    { 446, 3, "habitación", 10 },
                    { 447, 2, "habitual", 8 },
                    { 448, 2, "hablar", 6 },
                    { 449, 1, "hacer", 5 },
                    { 450, 1, "hacia", 5 },
                    { 451, 2, "hallar", 6 },
                    { 452, 1, "hasta", 5 },
                    { 453, 1, "hecha", 5 },
                    { 454, 1, "hecho", 5 },
                    { 455, 2, "hermana", 7 },
                    { 456, 2, "hermano", 7 },
                    { 457, 2, "hermosa", 7 },
                    { 458, 2, "hermoso", 7 },
                    { 459, 1, "hija", 4 },
                    { 460, 1, "hijo", 4 },
                    { 461, 2, "historia", 8 },
                    { 462, 3, "histórico", 9 },
                    { 463, 2, "hombre", 6 },
                    { 464, 2, "hombro", 6 },
                    { 465, 1, "hora", 4 },
                    { 466, 1, "hoy", 3 },
                    { 467, 2, "humana", 6 },
                    { 468, 2, "humano", 6 },
                    { 469, 1, "idea", 4 },
                    { 470, 2, "iglesia", 7 },
                    { 471, 1, "igual", 5 },
                    { 472, 2, "imagen", 6 },
                    { 473, 2, "imaginar", 8 },
                    { 474, 2, "impedir", 7 },
                    { 475, 2, "imponer", 7 },
                    { 476, 3, "importancia", 11 },
                    { 477, 3, "importante", 10 },
                    { 478, 2, "importar", 8 },
                    { 479, 3, "imposible", 9 },
                    { 480, 2, "imágenes", 8 },
                    { 481, 2, "incluir", 7 },
                    { 482, 2, "incluso", 7 },
                    { 483, 2, "indicar", 7 },
                    { 484, 3, "individuo", 9 },
                    { 485, 4, "informaciones", 13 },
                    { 486, 3, "información", 11 },
                    { 487, 2, "informar", 8 },
                    { 488, 2, "inglesa", 7 },
                    { 489, 2, "inglés", 6 },
                    { 490, 2, "iniciar", 7 },
                    { 491, 3, "inmediata", 9 },
                    { 492, 3, "inmediato", 9 },
                    { 493, 2, "insistir", 8 },
                    { 494, 2, "instante", 8 },
                    { 495, 2, "intentar", 8 },
                    { 496, 3, "interesar", 9 },
                    { 497, 3, "intereses", 9 },
                    { 498, 2, "interior", 8 },
                    { 499, 4, "internacional", 13 },
                    { 500, 2, "interés", 7 },
                    { 501, 3, "introducir", 10 },
                    { 502, 3, "izquierda", 9 },
                    { 503, 1, "jamás", 5 },
                    { 504, 1, "jefa", 4 },
                    { 505, 1, "jefe", 4 },
                    { 506, 1, "joven", 5 },
                    { 507, 1, "juego", 5 },
                    { 508, 2, "jugador", 7 },
                    { 509, 1, "jugar", 5 },
                    { 510, 2, "juicio", 6 },
                    { 511, 1, "junto", 5 },
                    { 512, 1, "justo", 5 },
                    { 513, 1, "labio", 5 },
                    { 514, 1, "lado", 4 },
                    { 515, 2, "lanzar", 6 },
                    { 516, 1, "largo", 5 },
                    { 517, 2, "lector", 6 },
                    { 518, 2, "lectora", 7 },
                    { 519, 1, "leer", 4 },
                    { 520, 2, "lengua", 6 },
                    { 521, 2, "lenguaje", 8 },
                    { 522, 1, "lento", 5 },
                    { 523, 2, "levantar", 8 },
                    { 524, 1, "ley", 3 },
                    { 525, 2, "libertad", 8 },
                    { 526, 1, "libre", 5 },
                    { 527, 1, "libro", 5 },
                    { 528, 2, "limitar", 7 },
                    { 529, 3, "literatura", 10 },
                    { 530, 2, "llamar", 6 },
                    { 531, 2, "llegar", 6 },
                    { 532, 2, "llenar", 6 },
                    { 533, 1, "lleno", 5 },
                    { 534, 2, "llevar", 6 },
                    { 535, 2, "llorar", 6 },
                    { 536, 1, "loca", 4 },
                    { 537, 1, "loco", 4 },
                    { 538, 2, "lograr", 6 },
                    { 539, 1, "lucha", 5 },
                    { 540, 1, "luego", 5 },
                    { 541, 1, "lugar", 5 },
                    { 542, 1, "luz", 3 },
                    { 543, 1, "línea", 5 },
                    { 544, 1, "madre", 5 },
                    { 545, 1, "mal", 3 },
                    { 546, 1, "mala", 4 },
                    { 547, 1, "malo", 4 },
                    { 548, 2, "mandar", 6 },
                    { 549, 2, "manera", 6 },
                    { 550, 3, "manifestar", 10 },
                    { 551, 1, "mano", 4 },
                    { 552, 2, "mantener", 8 },
                    { 553, 1, "mar", 3 },
                    { 554, 2, "marcar", 6 },
                    { 555, 2, "marcha", 6 },
                    { 556, 2, "marchar", 7 },
                    { 557, 2, "marido", 6 },
                    { 558, 1, "mas", 3 },
                    { 559, 1, "masa", 4 },
                    { 560, 1, "matar", 5 },
                    { 561, 2, "materia", 7 },
                    { 562, 2, "material", 8 },
                    { 563, 1, "mayor", 5 },
                    { 564, 2, "mayoría", 7 },
                    { 565, 2, "mañana", 6 },
                    { 566, 1, "media", 5 },
                    { 567, 2, "mediante", 8 },
                    { 568, 2, "medida", 6 },
                    { 569, 1, "medio", 5 },
                    { 570, 1, "mejor", 5 },
                    { 571, 2, "memoria", 7 },
                    { 572, 1, "menor", 5 },
                    { 573, 1, "menos", 5 },
                    { 574, 2, "menudo", 6 },
                    { 575, 2, "mercado", 7 },
                    { 576, 2, "merecer", 7 },
                    { 577, 1, "mes", 3 },
                    { 578, 1, "mesa", 4 },
                    { 579, 1, "meter", 5 },
                    { 580, 1, "metro", 5 },
                    { 581, 1, "miedo", 5 },
                    { 582, 2, "miembro", 7 },
                    { 583, 2, "mientras", 8 },
                    { 584, 1, "mil", 3 },
                    { 585, 2, "militar", 7 },
                    { 586, 2, "millón", 6 },
                    { 587, 2, "ministra", 8 },
                    { 588, 2, "ministro", 8 },
                    { 589, 2, "minuto", 6 },
                    { 590, 2, "mirada", 6 },
                    { 591, 1, "mirar", 5 },
                    { 592, 1, "mismo", 5 },
                    { 593, 1, "mitad", 5 },
                    { 594, 2, "modelo", 6 },
                    { 595, 2, "moderna", 7 },
                    { 596, 2, "moderno", 7 },
                    { 597, 1, "modo", 4 },
                    { 598, 2, "momento", 7 },
                    { 599, 1, "moral", 5 },
                    { 600, 1, "morir", 5 },
                    { 601, 2, "mostrar", 7 },
                    { 602, 2, "motivo", 6 },
                    { 603, 1, "mover", 5 },
                    { 604, 3, "movimiento", 10 },
                    { 605, 2, "muchacha", 8 },
                    { 606, 2, "muchacho", 8 },
                    { 607, 1, "mucho", 5 },
                    { 608, 2, "muerte", 6 },
                    { 609, 1, "mujer", 5 },
                    { 610, 2, "mujeres", 7 },
                    { 611, 2, "mundial", 7 },
                    { 612, 1, "mundo", 5 },
                    { 613, 2, "máquina", 7 },
                    { 614, 1, "más", 3 },
                    { 615, 2, "máximo", 6 },
                    { 616, 2, "médica", 6 },
                    { 617, 2, "médico", 6 },
                    { 618, 2, "método", 6 },
                    { 619, 2, "mínima", 6 },
                    { 620, 2, "mínimo", 6 },
                    { 621, 2, "música", 6 },
                    { 622, 1, "nacer", 5 },
                    { 623, 2, "nacional", 8 },
                    { 624, 1, "nada", 4 },
                    { 625, 1, "nadie", 5 },
                    { 626, 2, "natural", 7 },
                    { 627, 3, "naturaleza", 10 },
                    { 628, 3, "necesaria", 9 },
                    { 629, 3, "necesario", 9 },
                    { 630, 3, "necesidad", 9 },
                    { 631, 3, "necesitar", 9 },
                    { 632, 1, "negar", 5 },
                    { 633, 2, "negocio", 7 },
                    { 634, 1, "negra", 5 },
                    { 635, 1, "negro", 5 },
                    { 636, 2, "ninguna", 7 },
                    { 637, 2, "ninguno", 7 },
                    { 638, 2, "ningún", 6 },
                    { 639, 1, "nivel", 5 },
                    { 640, 1, "niña", 4 },
                    { 641, 1, "niño", 4 },
                    { 642, 1, "noche", 5 },
                    { 643, 2, "nombre", 6 },
                    { 644, 2, "normal", 6 },
                    { 645, 4, "norteamericana", 14 },
                    { 646, 4, "norteamericano", 14 },
                    { 647, 1, "notar", 5 },
                    { 648, 2, "noticia", 7 },
                    { 649, 2, "novela", 6 },
                    { 650, 2, "nuestra", 7 },
                    { 651, 2, "nuestro", 7 },
                    { 652, 1, "nueva", 5 },
                    { 653, 1, "nuevo", 5 },
                    { 654, 1, "nunca", 5 },
                    { 655, 2, "número", 6 },
                    { 656, 2, "objetivo", 8 },
                    { 657, 2, "objeto", 6 },
                    { 658, 2, "obligar", 7 },
                    { 659, 1, "obra", 4 },
                    { 660, 2, "observar", 8 },
                    { 661, 2, "obtener", 7 },
                    { 662, 3, "ocasiones", 9 },
                    { 663, 2, "ocasión", 7 },
                    { 664, 1, "ocho", 4 },
                    { 665, 2, "ocupar", 6 },
                    { 666, 2, "ocurrir", 7 },
                    { 667, 2, "oficial", 7 },
                    { 668, 2, "ofrecer", 7 },
                    { 669, 1, "ojo", 3 },
                    { 670, 2, "olvidar", 7 },
                    { 671, 3, "operación", 9 },
                    { 672, 2, "opinión", 7 },
                    { 673, 2, "origen", 6 },
                    { 674, 1, "oro", 3 },
                    { 675, 2, "orígenes", 8 },
                    { 676, 2, "oscura", 6 },
                    { 677, 2, "oscuro", 6 },
                    { 678, 1, "otra", 4 },
                    { 679, 1, "otro", 4 },
                    { 680, 1, "oír", 3 },
                    { 681, 2, "paciente", 8 },
                    { 682, 1, "padre", 5 },
                    { 683, 1, "pagar", 5 },
                    { 684, 2, "palabra", 7 },
                    { 685, 1, "papel", 5 },
                    { 686, 1, "par", 3 },
                    { 687, 1, "para", 4 },
                    { 688, 1, "parar", 5 },
                    { 689, 2, "parecer", 7 },
                    { 690, 1, "pared", 5 },
                    { 691, 2, "pareja", 6 },
                    { 692, 1, "parte", 5 },
                    { 693, 3, "participar", 10 },
                    { 694, 3, "particular", 10 },
                    { 695, 2, "partido", 7 },
                    { 696, 2, "partir", 6 },
                    { 697, 1, "pasa", 4 },
                    { 698, 2, "pasado", 6 },
                    { 699, 1, "pasar", 5 },
                    { 700, 1, "paso", 4 },
                    { 701, 1, "paz", 3 },
                    { 702, 1, "país", 4 },
                    { 703, 2, "países", 6 },
                    { 704, 1, "pecho", 5 },
                    { 705, 1, "pedir", 5 },
                    { 706, 2, "peligro", 7 },
                    { 707, 1, "pelo", 4 },
                    { 708, 2, "película", 8 },
                    { 709, 1, "pena", 4 },
                    { 710, 3, "pensamiento", 11 },
                    { 711, 2, "pensar", 6 },
                    { 712, 1, "peor", 4 },
                    { 713, 2, "pequeña", 7 },
                    { 714, 2, "pequeño", 7 },
                    { 715, 2, "perder", 6 },
                    { 716, 2, "perfecto", 8 },
                    { 717, 3, "periodista", 10 },
                    { 718, 3, "periódica", 9 },
                    { 719, 3, "periódico", 9 },
                    { 720, 3, "permanecer", 10 },
                    { 721, 2, "permitir", 8 },
                    { 722, 1, "pero", 4 },
                    { 723, 1, "perra", 5 },
                    { 724, 1, "perro", 5 },
                    { 725, 2, "persona", 7 },
                    { 726, 3, "personaje", 9 },
                    { 727, 2, "personal", 8 },
                    { 728, 3, "pertenecer", 10 },
                    { 729, 1, "pesar", 5 },
                    { 730, 1, "peso", 4 },
                    { 731, 1, "pie", 3 },
                    { 732, 2, "piedra", 6 },
                    { 733, 1, "piel", 4 },
                    { 734, 2, "pierna", 6 },
                    { 735, 1, "piso", 4 },
                    { 736, 2, "placer", 6 },
                    { 737, 1, "plan", 4 },
                    { 738, 2, "plantear", 8 },
                    { 739, 1, "plaza", 5 },
                    { 740, 1, "pleno", 5 },
                    { 741, 3, "poblaciones", 11 },
                    { 742, 3, "población", 9 },
                    { 743, 1, "pobre", 5 },
                    { 744, 1, "poca", 4 },
                    { 745, 1, "poco", 4 },
                    { 746, 1, "poder", 5 },
                    { 747, 2, "policía", 7 },
                    { 748, 2, "política", 8 },
                    { 749, 2, "político", 8 },
                    { 750, 1, "poner", 5 },
                    { 751, 2, "porque", 6 },
                    { 752, 2, "poseer", 6 },
                    { 753, 3, "posibilidad", 11 },
                    { 754, 2, "posible", 7 },
                    { 755, 3, "posiciones", 10 },
                    { 756, 2, "posición", 8 },
                    { 757, 2, "precio", 6 },
                    { 758, 2, "precisa", 7 },
                    { 759, 2, "preciso", 7 },
                    { 760, 2, "preferir", 8 },
                    { 761, 2, "pregunta", 8 },
                    { 762, 3, "preguntar", 9 },
                    { 763, 2, "prensa", 6 },
                    { 764, 3, "preocupar", 9 },
                    { 765, 2, "preparar", 8 },
                    { 766, 3, "presencia", 9 },
                    { 767, 3, "presentar", 9 },
                    { 768, 2, "presente", 8 },
                    { 769, 3, "presidente", 10 },
                    { 770, 3, "pretender", 9 },
                    { 771, 2, "primer", 6 },
                    { 772, 2, "primera", 7 },
                    { 773, 2, "primero", 7 },
                    { 774, 3, "principal", 9 },
                    { 775, 3, "principio", 9 },
                    { 776, 2, "privar", 6 },
                    { 777, 2, "probable", 8 },
                    { 778, 2, "problema", 8 },
                    { 779, 2, "proceso", 7 },
                    { 780, 2, "producir", 8 },
                    { 781, 2, "producto", 8 },
                    { 782, 3, "profesional", 11 },
                    { 783, 2, "profesor", 8 },
                    { 784, 3, "profesora", 9 },
                    { 785, 2, "profunda", 8 },
                    { 786, 2, "profundo", 8 },
                    { 787, 2, "programa", 8 },
                    { 788, 2, "pronta", 6 },
                    { 789, 2, "pronto", 6 },
                    { 790, 2, "propia", 6 },
                    { 791, 2, "propio", 6 },
                    { 792, 2, "proponer", 8 },
                    { 793, 2, "provocar", 8 },
                    { 794, 2, "proyecto", 8 },
                    { 795, 2, "prueba", 6 },
                    { 796, 2, "práctico", 8 },
                    { 797, 2, "próxima", 7 },
                    { 798, 2, "próximo", 7 },
                    { 799, 2, "publicar", 8 },
                    { 800, 2, "pueblo", 6 },
                    { 801, 2, "puerta", 6 },
                    { 802, 1, "pues", 4 },
                    { 803, 2, "puesto", 6 },
                    { 804, 1, "punto", 5 },
                    { 805, 1, "pura", 4 },
                    { 806, 1, "puro", 4 },
                    { 807, 2, "página", 6 },
                    { 808, 2, "pública", 7 },
                    { 809, 2, "público", 7 },
                    { 810, 2, "quedar", 6 },
                    { 811, 2, "querer", 6 },
                    { 812, 1, "quien", 5 },
                    { 813, 2, "quitar", 6 },
                    { 814, 1, "quizá", 5 },
                    { 815, 1, "quién", 5 },
                    { 816, 1, "radio", 5 },
                    { 817, 1, "rato", 4 },
                    { 818, 2, "razones", 7 },
                    { 819, 1, "razón", 5 },
                    { 820, 2, "realidad", 8 },
                    { 821, 2, "realizar", 8 },
                    { 822, 2, "recibir", 7 },
                    { 823, 2, "reciente", 8 },
                    { 824, 2, "recoger", 7 },
                    { 825, 3, "reconocer", 9 },
                    { 826, 2, "recordar", 8 },
                    { 827, 2, "recorrer", 8 },
                    { 828, 2, "recuerdo", 8 },
                    { 829, 3, "recuperar", 9 },
                    { 830, 2, "reducir", 7 },
                    { 831, 2, "referir", 7 },
                    { 832, 2, "regresar", 8 },
                    { 833, 3, "relaciones", 10 },
                    { 834, 2, "relación", 8 },
                    { 835, 3, "religiosa", 9 },
                    { 836, 3, "religioso", 9 },
                    { 837, 2, "repetir", 7 },
                    { 838, 3, "representar", 11 },
                    { 839, 2, "resolver", 8 },
                    { 840, 3, "responder", 9 },
                    { 841, 3, "responsable", 11 },
                    { 842, 3, "respuesta", 9 },
                    { 843, 1, "resto", 5 },
                    { 844, 3, "resultado", 9 },
                    { 845, 2, "resultar", 8 },
                    { 846, 3, "reuniones", 9 },
                    { 847, 2, "reunir", 6 },
                    { 848, 2, "reunión", 7 },
                    { 849, 2, "revista", 7 },
                    { 850, 1, "rey", 3 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_PlayerGames_GuessWordId",
                table: "PlayerGames",
                column: "GuessWordId");

            migrationBuilder.CreateIndex(
                name: "IX_PlayerGames_PlayerId",
                table: "PlayerGames",
                column: "PlayerId");

            migrationBuilder.CreateIndex(
                name: "IX_PlayerScores_PlayerId",
                table: "PlayerScores",
                column: "PlayerId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PlayerGames");

            migrationBuilder.DropTable(
                name: "PlayerScores");

            migrationBuilder.DropTable(
                name: "GuessWords");

            migrationBuilder.DropTable(
                name: "Players");
        }
    }
}
